FROM php:8.2.3-apache

RUN apt-get update && \
    apt-get install -y curl git unzip libzip-dev libonig-dev

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN chown -R www-data:www-data /var/www/html/ && \
    chmod -R 755 /var/www/html/

WORKDIR /var/www/html

RUN apt update && apt install git

# RUN composer install && composer dump-autoload

RUN echo "DocumentRoot /var/www/html/public" > /etc/apache2/sites-enabled/000-default.conf

# RUN a2enmod rewrite

# RUN php artisan serve

EXPOSE 81


# CMD ["php", "artisan", "serve"]
CMD ["apache2-foreground"]
