version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: php
    command: ./script.sh
    volumes:
      - .:/var/www/html
    ports:
      - "81:8000"
  
