version: '3.9'
services: 

  laravel-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 81:80
    restart: always
    command: ./script.sh
    volumes:
      - .:/var/www/html/